name: flutter_custom_slidable
description: Custom slidable
version: 0.0.1



environment:
  sdk: ">=2.17.6 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true